apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-moderation-backend
  labels:
    app: content-moderation
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content-moderation
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: content-moderation
        tier: backend
    spec:
      containers:
      - name: backend
        image: ${DOCKER_REGISTRY}/content-moderation-backend:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: NODE_ENV
          value: "production"
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: content-moderation-config
              key: frontend_url
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: content-moderation-secrets
              key: database_url
        - name: CLERK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: content-moderation-secrets
              key: clerk_secret_key
        - name: EMAIL_SERVICE
          valueFrom:
            configMapKeyRef:
              name: content-moderation-config
              key: email_service
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: content-moderation-secrets
              key: email_user
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: content-moderation-secrets
              key: email_password
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: content-moderation-config
              key: redis_url
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: content-moderation-secrets
              key: sentry_dsn
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: content-moderation-backend
  labels:
    app: content-moderation
    tier: backend
spec:
  selector:
    app: content-moderation
    tier: backend
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP